# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='e.g. /auth/signin/', max_length=255, verbose_name='path')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], max_length=20)),
                ('status', models.CharField(choices=[('200', '200'), ('404', '404'), ('503', '503')], max_length=20)),
                ('response', models.TextField(verbose_name='response')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='is enabled')),
            ],
            options={
                'ordering': ('path',),
            },
        ),
    ]
